#import BG_Hero_powers as Hero_Power

hero_armor_map = {
    'Reno_Jackson': 5,
    'Ysera': 2,
    'Dancin_Deryl': 3,
    'Rakanishu': 1,
    'Patchwerk': 10,
    'C Thun': 3,
    'Millificent_Manastorm': 4,
    'Patches_the_Pirate': 4,
    'Sindragosa': 3,
    'The_Lich_King': 5,
    'Nefarian': 2,
    'Bartendotron': 4,
    'George_the_Fallen': 3,
    'Lich_Baz hial': 0,
    'Nozdormu': 2,
    'Rat_King': 4,
    'King_Mukla': 4,
    'A. F. Kay': 0,
    'Lord_Jaraxxus': 3,
    'Queen_Wagtoggle': 5,
    'Captain_Hooktusk': 5,
    'Galakrond': 2,
    'Silas_Darkmoon': 4,
    'Malygos': 3,
    'Cariel_Roame': 3,
    'Kurtrus_Ashfallen': 4,
    'Arch-Villain_Rafaam': 3,
    'Mr. Bigglesworth': 1,
    'Greybough': 4,
    'Xyrella': 4,
    'Tamsin_Roame': 5,
    'Skycap n_Kragg': 6,
    'Barov': 4,
    'Varden_Dawngrasp': 2,
    'Zephrys': 1,
    'Cariel_Roame': 3,
    'Tess_Greymane': 3,
    'Reno_Jackson': 5
}

hero_power_map = {
    'Reno_Jackson': 1, #Hero_Power.Reno_Jackson(),
    'Ysera': 2,
    'Dancin_Deryl': 3,
    'Rakanishu': 1,
    'Patchwerk': 10,
    'C Thun': 3,
    'Millificent_Manastorm': 4,
    'Patches_the_Pirate': 4,
    'Sindragosa': 3,
    'The_Lich_King': 5,
    'Nefarian': 2,
    'Bartendotron': 4,
    'George_the_Fallen': 3,
    'Lich_Baz hial': 0,
    'Nozdormu': 2,
    'Rat_King': 4,
    'King_Mukla': 4,
    'A. F. Kay': 0,
    'Lord_Jaraxxus': 3,
    'Queen_Wagtoggle': 5,
    'Captain_Hooktusk': 5,
    'Galakrond': 2,
    'Silas_Darkmoon': 4,
    'Malygos': 3,
    'Cariel_Roame': 3,
    'Kurtrus_Ashfallen': 4,
    'Arch-Villain_Rafaam': 3,
    'Mr. Bigglesworth': 1,
    'Greybough': 4,
    'Xyrella': 4,
    'Tamsin_Roame': 5,
    'Skycap n_Kragg': 6,
    'Barov': 4,
    'Varden_Dawngrasp': 2,
    'Zephrys': 1,
    'Cariel_Roame': 3,
    'Tess_Greymane': 3,
    'Reno_Jackson': 5
}

heroes_list = list(hero_armor_map.keys())